/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jpane;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class UI
        extends javax.swing.JFrame
{

    /**
     * Creates new form UI
     */
    public UI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jBConfirm = new javax.swing.JButton();
        jbEntrada = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jOpciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaResultados = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBConfirm.setText("Confirmar");
        jBConfirm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBConfirmActionPerformed(evt);
            }
        });

        jbEntrada.setText("Entrada");
        jbEntrada.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbEntradaActionPerformed(evt);
            }
        });

        jButton3.setText("Mensajes");

        jOpciones.setText("Opciones");
        jOpciones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jOpcionesActionPerformed(evt);
            }
        });

        jtaResultados.setColumns(20);
        jtaResultados.setRows(5);
        jScrollPane1.setViewportView(jtaResultados);

        jLabel1.setText(" Dialog frames");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jOpciones)))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBConfirm)
                                .addGap(29, 29, 29)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jBConfirm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbEntrada)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jOpciones)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBConfirmActionPerformed
    {//GEN-HEADEREND:event_jBConfirmActionPerformed
        int valor;
        //TIPO 1
        jtaResultados.setText("");
        valor = JOptionPane.showConfirmDialog(this,
                "¿Confirmas movimiento?");
        jtaResultados.setText("Respuesta de movimiento:" + valor);
        //TIPO 2
        valor = JOptionPane.showConfirmDialog(this,
                "¿Borrar Datos?");
        jtaResultados.setText(
                jtaResultados.getText() + "\nRespuesta a borrar" + valor);
        //TIPO 3
        valor = JOptionPane.showConfirmDialog(this,
                "Autoriza el cambio",
                "Confiramcion",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        jtaResultados.setText(
                jtaResultados.getText() + "\nRespuesta de Cambio" + valor);
        //TIPO 4
        ImageIcon icono = new ImageIcon("src/jpane/casa.png");
        JOptionPane.showConfirmDialog(this,
                "Autoriza el cambio",
                "Confiramcion",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        jtaResultados.setText(
                jtaResultados.getText() + "\nRespuesta de Cambio" + valor);

    }//GEN-LAST:event_jBConfirmActionPerformed

    private void jbEntradaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbEntradaActionPerformed
    {//GEN-HEADEREND:event_jbEntradaActionPerformed
        String respuesta;
        int edad;
        jtaResultados.setText("");

        respuesta = JOptionPane.showInputDialog("Ingresa Nombre");
        jtaResultados.setText("Nombre " + respuesta + "\n");

        respuesta = JOptionPane.showInputDialog(this,
                "ingresa edad");
        edad = Integer.parseInt(respuesta);
        jtaResultados.append("Edad" + respuesta + "\n");

        respuesta = JOptionPane.showInputDialog(this,
                "Apellido Paterno",
                "Zuniga");
        jtaResultados.append("Paterno" + respuesta + "\n");

        respuesta = JOptionPane.showInputDialog(this,
                "Apellido Paterno",
                "Ojeda");
        jtaResultados.append("Materno" + respuesta + "\n");

        respuesta = JOptionPane.showInputDialog(this,
                "captura domicilio",
                "Dato de contacto",
                JOptionPane.INFORMATION_MESSAGE);
        jtaResultados.append("Domicilio" + respuesta + "\n");

        String opciones[] =
        {
            "Elige:", "Jalisco", "Sinaloa", "MIchoacan", "Yucatan"
        };
        ImageIcon icono = new ImageIcon("src/jpane/casa.png");
        respuesta = JOptionPane.showInputDialog(this,
                "Estado con el que colinda Jalisco:",
                "Pregunta",
                JOptionPane.PLAIN_MESSAGE,
                icono,
                opciones,
                "Elige").
                toString();
        jtaResultados.append("Estado:" + respuesta + "\n");
    }//GEN-LAST:event_jbEntradaActionPerformed

    private void jOpcionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jOpcionesActionPerformed
    {//GEN-HEADEREND:event_jOpcionesActionPerformed
        jtaResultados.setText("");

        String opciones[] =
        {
            "Alfa", "Beta", "Gama", "Epsilon", "Etha", "Otra"
        };
        ImageIcon icono = new ImageIcon("src/jpane/casa.png");
        int respuesta;

        respuesta = JOptionPane.showOptionDialog(this,
                "Elige una de las letras",
                "letras Griegas",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                icono,
                opciones,
                opciones[0]);
        jtaResultados.append(
                "Opcion numerica" + respuesta + "\n" + "Opcion textual" + opciones[respuesta]);
    }//GEN-LAST:event_jOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirm;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jOpciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEntrada;
    private javax.swing.JTextArea jtaResultados;
    // End of variables declaration//GEN-END:variables
}
